name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: auto_grade
      id: auto_grade
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        setup-command: pip install pytest; pytest test_main.py
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        AUTO_GRADE_RESULTS: "${{steps.auto_grade.outputs.result}}"
      with:
        runners: auto_grade
